version: 2

updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - ".github/actions/setup-test-dependencies"
      - ".github/actions/setup-website-dependencies"
    schedule:
      interval: "cron"
      cronjob: "30 7,12,17 * * *"
    target-branch: "main"
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "npm"
    directory: "website"
    schedule:
      interval: "cron"
      cronjob: "30 7,12,17 * * *"
    target-branch: "main"
    groups:
      typescript:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "uv"
    directory: "tests"
    schedule:
      interval: "cron"
      cronjob: "30 7,12,17 * * *"
    target-branch: "main"
    groups:
      python:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
