version: 2

updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
    schedule:
      interval: "daily"
      time: "01:00"
      timezone: "Europe/London"
    target-branch: "main"
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "npm"
    directory: "dashboard"
    schedule:
      interval: "daily"
      time: "01:00"
      timezone: "Europe/London"
    target-branch: "main"
    groups:
      typescript:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "uv"
    directory: "tests"
    schedule:
      interval: "daily"
      time: "01:00"
      timezone: "Europe/London"
    target-branch: "main"
    groups:
      python:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
