name: "Setup Website Dependencies"
description: "Installs dependencies for the project"

runs:
  using: "composite"
  steps:
    - name: Set up Node.js with Cache
      uses: actions/setup-node@v4.3.0
      with:
        node-version: "22.8.0"
        cache: "npm"
        cache-dependency-path: "website/package-lock.json"

    - name: Set up Just
      uses: extractions/setup-just@v3

    - name: Install Website Dependencies
      shell: bash
      run: just website::install
