name: Clean Caches

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

permissions: {}

jobs:
  clean-caches:
    name: Clean Caches
    permissions:
      contents: read
    uses: JackPlowman/reusable-workflows/.github/workflows/common-clean-caches.yml@248e14987652d9507c9ed16ad7fcd16d170afb66 # v2026.03.28.01
    secrets:
      workflow_github_token: ${{ secrets.GH_TOKEN }}
