name: "Sync labels"

on:
  push:
    branches:
      - main
    paths:
      - .github/tool-configurations/labels.yml
  workflow_dispatch:

permissions: {}

jobs:
  configure-labels:
    name: Configure Labels
    permissions:
      contents: read
      pull-requests: write
    uses: JackPlowman/reusable-workflows/.github/workflows/common-sync-labels.yml@a69e45a3f90bb2372d7851e569c5d54c3028ebe0 # v2026.02.27.01
    secrets:
      workflow_github_token: ${{ secrets.GITHUB_TOKEN }}
