name: "Sync labels"

on:
  push:
    branches:
      - main
    paths:
      - .github/tool-configurations/labels.yml
  workflow_dispatch:

permissions: {}

jobs:
  configure-labels:
    name: Configure Labels
    permissions:
      contents: read
      pull-requests: write
    uses: JackPlowman/reusable-workflows/.github/workflows/common-sync-labels.yml@248e14987652d9507c9ed16ad7fcd16d170afb66 # v2026.03.28.01
    secrets:
      workflow_github_token: ${{ secrets.GITHUB_TOKEN }}
