name: "Sync labels"

on:
  push:
    branches:
      - main
    paths:
      - .github/tool-configurations/labels.yml
  workflow_dispatch:

permissions: {}

jobs:
  configure-labels:
    name: Configure Labels
    permissions:
      contents: read
      pull-requests: write
    uses: JackPlowman/reusable-workflows/.github/workflows/common-sync-labels.yml@52b5547a80bbde1f87300170d9f129d7829f17c6 # v2026.07.11.02
    secrets:
      workflow_github_token: ${{ secrets.GITHUB_TOKEN }}
